package com.newpccms;


import com.newpccms.login;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANISH ARALIKATTI
 */
public class patient_reg extends javax.swing.JFrame {

    /**
     * Creates new form patient_reg
     */
    public patient_reg() {
        initComponents();
        bgpanel.setBackground(new Color(255,255,255,235));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        blp = new javax.swing.JButton();
        back = new javax.swing.JButton();
        bgpanel = new javax.swing.JPanel();
        fname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        uname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        phnum = new javax.swing.JTextField();
        addr = new javax.swing.JTextField();
        m = new javax.swing.JRadioButton();
        f = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        crpas1 = new javax.swing.JPasswordField();
        confpas2 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        reg = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        hei = new javax.swing.JTextField();
        wei = new javax.swing.JTextField();
        all = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        bg = new javax.swing.JComboBox<>();
        dat = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1175, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NEW PATIENT REGISTRATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 740, 40));

        blp.setText("BACK TO LOGIN PAGE ");
        blp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blpActionPerformed(evt);
            }
        });
        getContentPane().add(blp, new org.netbeans.lib.awtextra.AbsoluteConstraints(941, 20, 200, -1));

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, -1));

        bgpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bgpanel.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 87, 168, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("First Name");
        bgpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 168, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Last Name");
        bgpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 168, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("e-Mail");
        bgpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 168, 168, -1));
        bgpanel.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 137, 168, -1));
        bgpanel.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 188, 168, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Phone");
        bgpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 219, 168, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DOB");
        bgpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 168, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Address");
        bgpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 170, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Gender");
        bgpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 280, 140, -1));
        bgpanel.add(phnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 239, 168, -1));
        bgpanel.add(addr, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 168, 61));

        buttonGroup1.add(m);
        m.setText("Male");
        bgpanel.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, 20));

        buttonGroup1.add(f);
        f.setText("Female");
        bgpanel.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Create Password");
        bgpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 415, 170, 20));
        bgpanel.add(crpas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 168, -1));
        bgpanel.add(confpas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 168, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Confirm Password");
        bgpanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 470, 160, 30));

        reg.setText("REGISTER");
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });
        bgpanel.add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 140, 40));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel11.setText("Medical Details");
        bgpanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 11, 170, 27));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Height (in cm)");
        bgpanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 70, 140, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Weight (in kg)");
        bgpanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 120, 140, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Allergies");
        bgpanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 130, -1));

        hei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heiActionPerformed(evt);
            }
        });
        bgpanel.add(hei, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 134, -1));

        wei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weiActionPerformed(evt);
            }
        });
        bgpanel.add(wei, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 134, -1));
        bgpanel.add(all, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 134, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Blood Group");
        bgpanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 220, 140, -1));

        bg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "O +ve", "A +ve", "B +ve", "O -ve", "A -ve", "AB +ve", "B -ve", "AB -ve" }));
        bg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgActionPerformed(evt);
            }
        });
        bgpanel.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 134, -1));

        dat.setDateFormatString("yyyy-MM-dd");
        bgpanel.add(dat, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 291, 168, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/newpccms/logo.jpg"))); // NOI18N
        bgpanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, -1, 130));

        getContentPane().add(bgpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 740, 580));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(2192, 191, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/newpccms/rsz_computer-desk-doctor-48604 (1).jpg"))); // NOI18N
        jLabel17.setMaximumSize(new java.awt.Dimension(1200, 715));
        jLabel17.setPreferredSize(new java.awt.Dimension(1100, 750));
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
       
        
        String hashpas = null;
        int val = 1;
        int ind =  bg.getSelectedIndex();
        String u=uname.getText();
        String pas=new String(crpas1.getPassword());
        int lenpas1=pas.length();
        String pas2=new String(confpas2.getPassword());
        int lenpas2=pas2.length();
        String fna=fname.getText();
        String lna=lname.getText();
        String ph=phnum.getText();
        int p=ph.length();
        String ad=addr.getText();
        String he=hei.getText();
        String  we=wei.getText();
        String al=all.getText();
        DateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
        String da = fmt.format(dat.getDate());
        
         try 
         { 
  
            // Static getInstance method is called with hashing SHA 
            MessageDigest md = MessageDigest.getInstance("SHA-256"); 
  
            // digest() method called 
            // to calculate message digest of an input 
            // and return array of byte 
            byte[] messageDigest = md.digest(pas2.getBytes()); 
  
            // Convert byte array into signum representation 
            BigInteger no = new BigInteger(1, messageDigest); 
  
            // Convert message digest into hex value 
            String hashtext = no.toString(16); 
  
            while (hashtext.length() < 32) { 
                hashtext = "0" + hashtext; 
            } 
  
            hashpas = hashtext;
        } 
  
        // For specifying wrong message digest algorithms 
        catch (NoSuchAlgorithmException e) 
        { 
            System.out.println("Exception thrown"
                               + " for incorrect algorithm: " + e); 
  
            
        } 
        
        
 

        if(fna.equalsIgnoreCase("")==false)
        {
            if(lna.equalsIgnoreCase("")==false)
            {
                if(u.equalsIgnoreCase("")==false)
                {
                    if(ph.equalsIgnoreCase("")==false && p == 10)
                    {
                        if(da.equalsIgnoreCase("")==false)
                        {
                            if(ad.equalsIgnoreCase("")==false)
                            {
                                if(m.isSelected() || f.isSelected())
                                {
                                    if(he.equalsIgnoreCase("")==false)
                                    {
                                        int h=Integer.parseInt(he);
                                        if(h<=250&&h>=50)
                                        {
                                           if(we.equalsIgnoreCase("")==false)
                                            {
                                                int w=Integer.parseInt(we);
                                                if(w>=25 && w<250)
                                                {
                                                   if(ind != 0)
                                                    {
                                                        if(al.equalsIgnoreCase("") == false)
                                                        {
                                                            if(lenpas1>4) 
                                                            {
                                                                if(pas2.equalsIgnoreCase("")==false && (lenpas2 == lenpas1))
                                                                {
                                                                    if(pas.equals(pas2))
                                                                    {
                                                                        String bgp = null;
                                                                         if(ind == 1)
                                                                             bgp = "O+";
                                                                         else if(ind == 2)
                                                                             bgp = "A+";
                                                                         else if(ind == 3)
                                                                             bgp = "B+";
                                                                         else if(ind == 4)
                                                                             bgp = "O-";
                                                                         else if(ind == 5)
                                                                             bgp = "A-";
                                                                         else if(ind == 6)
                                                                             bgp = "AB+";
                                                                         else if(ind == 7)
                                                                             bgp = "B-";
                                                                         else if(ind == 8)
                                                                             bgp = "AB-";
                                                                         char ge;
                                                                         if(m.isSelected())
                                                                             ge='M';
                                                                         else
                                                                             ge='F';

                                                                         try
                                                                         {
                                                                             Class.forName("com.mysql.jdbc.Driver");
                                                                             String a="jdbc:mysql://localhost:3306/pccms";
                                                                             Connection con;
                                                                             con = (Connection)DriverManager.getConnection(a,"root","Password@1234");
                                                                             Statement stmt=(Statement)con.createStatement();
                                                                             Statement stm=(Statement)con.createStatement();
                                                                             String q1= "INSERT INTO patient(fname,lname,gender,dob,email,address,height,weight,bloodgrp,phone_num,allergicto) VALUES('"+fna+"','"+lna+"','"+ge+"','"+da+"','"+u+"','"+ad+"','"+h+"','"+w+"','"+bgp+"','"+ph+"','"+al+"');";
                                                                             stmt.executeUpdate(q1);
                                                                             String query="INSERT INTO login VALUES('"+u+"','"+hashpas+"','"+val+"');";
                                                                             stm.executeUpdate(query);
                                                                             reg.setVisible(false);
                                                                             blp.setVisible(true);
                                                                             JOptionPane.showMessageDialog(null,"You have successfully registered \n Please go back to login page!");



                                                                         }
                                                                         catch(Exception e)
                                                                         {
                                                                             JOptionPane.showMessageDialog(this,e.getMessage());
                                                                         }

                                                                    }
                                                                    else
                                                                    {
                                                                        JOptionPane.showMessageDialog(null,"Your passwords dont match.Please type them again!");
                                                                    }
                                                                }
                                                                else
                                                                {
                                                                    JOptionPane.showMessageDialog(null,"Your passwords dont match.Please type them again!");
                                                                }
                                                            }
                                                            else
                                                            {
                                                                JOptionPane.showMessageDialog(null,"Password should be minimum 5 characters long!");
                                                            }
                                                        }
                                                        else
                                                           JOptionPane.showMessageDialog(null,"Enter Allergies! If none enter 'NONE'!"); 
                                                    }
                                                   else
                                                       JOptionPane.showMessageDialog(null,"Select Blood Group!");
                                                }
                                                else
                                                    JOptionPane.showMessageDialog(null,"Invalid Weight!");
                                                
                                            }
                                           else
                                           {
                                               JOptionPane.showMessageDialog(null,"Enter weight!");
                                           }
                                        }
                                        else
                                            JOptionPane.showMessageDialog(null,"Invalid height!");
                                        
                                    }
                                    else 
                                        JOptionPane.showMessageDialog(null,"Enter height!");
                                }
                                else
                                    JOptionPane.showMessageDialog(null,"Select Gender!");
                                    
                            }
                            else
                                JOptionPane.showMessageDialog(null,"Enter address!");
                        }
                        else
                            JOptionPane.showMessageDialog(null,"Select Date of Birth!");
                    }
                    else
                        JOptionPane.showMessageDialog(null,"Enter valid mobile number!");
                 
                }
                else
                   JOptionPane.showMessageDialog(null,"Enter valid email address!");
            }      
            else
                JOptionPane.showMessageDialog(null,"Enter Last Name!");
        }
        else
            JOptionPane.showMessageDialog(null,"Enter First Name!");
        
        
        /*fname.setEditable(false);
        uname.setEditable(false);
        crpas1.setEditable(false);
        confpas2.setEditable(false);
        phnum.setEditable(false);
        addr.setEditable(false);
        hei.setEditable(false);
        wei.setEditable(false);
        all.setEditable(false);
        bg.setEditable(false);
        lname.setEditable(false);
        dat.setEnabled(false);
        back.setVisible(false);*/
    }//GEN-LAST:event_regActionPerformed

    private void bgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bgActionPerformed

    private void heiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heiActionPerformed
        
    }//GEN-LAST:event_heiActionPerformed

    private void blpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blpActionPerformed
       close();
       login v=new login();
       v.setVisible(true);
      
    }//GEN-LAST:event_blpActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        close();
       login v=new login();
       v.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void weiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patient_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patient_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patient_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patient_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new patient_reg().setVisible(true);
                
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addr;
    private javax.swing.JTextField all;
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> bg;
    private javax.swing.JPanel bgpanel;
    public javax.swing.JButton blp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPasswordField confpas2;
    private javax.swing.JPasswordField crpas1;
    public com.toedter.calendar.JDateChooser dat;
    private javax.swing.JRadioButton f;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField hei;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lname;
    private javax.swing.JRadioButton m;
    private javax.swing.JTextField phnum;
    private javax.swing.JButton reg;
    private javax.swing.JTextField uname;
    private javax.swing.JTextField wei;
    // End of variables declaration//GEN-END:variables


public void close()
    {
WindowEvent winClosingEvent= new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);


}
    
    
} 

